### PR TITLE
DtlsCert not implement Clone

### PR DESCRIPTION
**Pull request by algesten**

### CODE REVIEW

**Comment by algesten** [comment]
@xnorpx I don't know if you relied on cloning the `DtlsCert` in your things. There is an escape hatch.

**Review by morajabi — APPROVED** [review]

**Comment by k0nserv** [comment]
Why is it a security risk to reuse the certificate? DTLS is just stream oriented TLS, and under TLS certificates are reused all the time after all.

**Comment by lolgesten** [comment]
Hm. You might have a point here. 🤔

**Comment by lolgesten** [comment]
Tried to researching if there been any recommendations on this. Can't find any.

Slack had a problem of a fixed well known private key, which is tangential but not the same case: https://hackerone.com/reports/531032

**Comment by xnorpx** [comment]
Afaik reusing cert on server for multiple connections is standard practice. But you should generate new certs for each connection on the clients.

This is something we do rely on, creation of str0m essentially becomes blocking call if we can't clone it on the server.

Remove Clone and have specific API is probably fine. But I would probably name it more clear.

pub fn clone_for_multiple_connections_on_server(&self) -> DtlsCert {
    DtlsCert {
        pkey: self.pkey.clone(),
        x509: self.x509.clone(),
    }
}

**Pull request closed without merging**
