### PR TITLE
Added FAQ

### PR DESCRIPTION
**Pull request by xnorpx**
first stab to add some faq

### CODE REVIEW

**Comment by algesten** [comment]
Nice! I like where you're going with this!

**Comment by algesten** [comment]
@xnorpx just realised this needs to move. The README.md is generated using `cargo readme > README.md`

The actual contents is in the start of `lib.rs`

**Comment by xnorpx** [comment]
ah let me move and fix that

**Comment by xnorpx** [comment]
moved to lib.rs and generated README.md

**Comment by algesten** [comment]
Thanks!

**Pull request merged**
