### PR TITLE
fix: use a `const fn`  to compute the overall STUN timeout

### PR DESCRIPTION
**Pull request by thomaseizinger**

### CODE REVIEW

**Review by algesten — APPROVED** [review]
LGTM!

Thanks!

**Comment by thomaseizinger** [comment]
I pushed another version where I am just testing the constant. Less invasive.

What do you prefer?

**Comment by algesten** [comment]
Neat.

I did like the test in the previous as well :)

**Comment by thomaseizinger** [comment]
I am leaning towards just testing the constant until we get better const arithemtic support :)

**Comment by algesten** [comment]
Thanks

**Pull request merged**
