### PR TITLE
Fix `ChannelId` allocation

### PR DESCRIPTION
**Pull request by altonen**
Previously `ChannelHandler` used the number of active channels to derive the next `ChannelId`. This resulted in two channels getting assigned the same `ChannelId` because the allocation didn't track which `ChannelId`s were free to be reused. For example, when two channels were created, allocating channel IDs 0 and 1, `ChannelId(0)` was freed and then a new channel was created, this new channel had an ID 1, which was already in use.

Start using a `usize` counter to allocate channel IDs, ensuring they're unique

### CODE REVIEW

**Comment by altonen** [comment]
@algesten friendly ping

does it look good to you or is there some blocker?

**Comment by algesten** [comment]
Can we make a simpler version that just keeps increasing the number? No Reuse?

**Comment by altonen** [comment]
> Can we make a simpler version that just keeps increasing the number? No Reuse?

Done

**Review by algesten — APPROVED** [review]
LGTM!

Thanks!

**Pull request merged**
