### PR TITLE
feature/twcc record packet status

### PR DESCRIPTION
**Pull request by k0nserv**
- Record packet status in SendRecord
- Account for packet status for bitrate estimates

### CODE REVIEW

**Review by algesten — APPROVED** [review]
It's getting a bit state heavy. But I can clean that up later.

**Comment by k0nserv** [comment]
> It's getting a bit state heavy. But I can clean that up later.

Do you mean `SendRecord` or the return type on the iterator(I was thinking that might be due to become a struct)?

**Comment by algesten** [comment]
More the interaction between all the fields. The status vs instant. They both encode an implicit state that we received feedback. Would be nice to make that explicit.

**Comment by k0nserv** [comment]
> More the interaction between all the fields. The status vs instant. They both encode an implicit state that we received feedback. Would be nice to make that explicit.

Ah yes I was thinking that too, something like


```rust
struct SendRecord {
  seq_no: SeqNo,
  local_send_time: Instant,
  size: u16,
  recv_report: Option<RecvReport>
}
```

**Comment by algesten** [comment]
Yeah. That's nice.

**Comment by k0nserv** [comment]
> can any of this go out in the stats ?
No I don't think anything here is needed for stats

> Yeah. That's nice.
I can move it to something like that next time I touch the code

**Pull request merged**
